name: demo_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  assets_audio_player: ^1.6.0+4
  flutter_sound: ^5.0.0
  permission_handler: ">=5.0.0 <6.0.0"
  path_provider: ^1.6.1
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - res/icons/ic_play.png
    - res/icons/ic_play_disabled.png
    - res/icons/2.0x/ic_play.png
    - res/icons/3.0x/ic_play.png
    - res/icons/ic_stop.png
    - res/icons/ic_stop_disabled.png
    - res/icons/2.0x/ic_stop.png
    - res/icons/3.0x/ic_stop.png
    - res/icons/ic_pause.png
    - res/icons/ic_pause_disabled.png
    - res/icons/2.0x/ic_pause.png
    - res/icons/3.0x/ic_pause.png
    - res/icons/ic_mic.png
    - res/icons/ic_mic_disabled.png
    - res/icons/2.0x/ic_mic.png
    - res/icons/3.0x/ic_mic.png
    - res/icons/ic_volume_down.png
    - res/icons/2.0x/ic_volume_down.png
    - res/icons/3.0x/ic_volume_down.png
    - res/icons/ic_volume_up.png
    - res/icons/2.0x/ic_volume_up.png
    - res/icons/3.0x/ic_volume_up.png

    - assets/samples/
    - assets/canardo.png
    - assets/